version: "3.9"

services:
  shell:
    build: ./shell
    container_name: mfe_shell
    ports:
      - "5173:5173"
    environment:
      - PORT=5173

  auth:
    build: ./auth
    container_name: mfe_auth
    ports:
      - "5174:5174"
    environment:
      - PORT=5174

  classes:
    build: ./classes
    container_name: mfe_classes
    ports:
      - "5175:5175"
    environment:
      - PORT=5175

  tasks:
    build: ./tasks
    container_name: mfe_tasks
    ports:
      - "5176:5176"
    environment:
      - PORT=5176
      
  grades:
    build: ./grades
    container_name: mfe_grades
    ports:
      - "5177:5177"
    environment:
      - PORT=5177
